name: bank_services
services:
  database:
    container_name: bank_database
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      "MYSQL_ROOT_PASSWORD": "root123"
      "MYSQL_DATABASE": "bank_db" # use to set in DBeaver