spring:

  application:
    name: bank

  datasource:
    url: jdbc:mysql://localhost:3306/bank_db # DB URL
    driver: com.mysql.cj.jdbc.Driver # On Dbeaver, Driver settings > Class name
    username: "root"
    password: "root123"

  jpa:
    hibernate:
      ddl-auto: update